### get data personal
GET http://localhost:8888/rest/em/personal
Authorization: Bearer {{$global.accessToken}}

### get personal by user id
GET http://localhost:8888/rest/em/personal/8
Authorization: Bearer {{$global.accessToken}}

### update personal
PUT http://localhost:8888/rest/em/personal/8
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
    "name":"Pojok Code",
    "email":"code@gmail.com",
    "age":30
}

### create personal without user akun
POST http://localhost:8888/rest/em/personal
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
    "name":"Pojok Code",
    "email":"codex@gmail.com",
    "age":30
}

### delete personal 
DELETE http://localhost:8888/rest/em/personal/9
Authorization: Bearer {{$global.accessToken}}