### load key
GET http://localhost:8888/
### say hello
GET http://localhost:8888/rest/em/user/say
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJEQVRBIjoiUG9qb2sgQ29kZSIsIkVYUCI6MTc0NDYyMDMzNywiVFMiOiJBcHJpbCwgMTQgMjAyNSAxNToxNTozNyArMDcwMCJ9.vn8OwjtL-9GtUJmkdyarBfywqHXvpvNG-FWqLe2yo0k