@base_url=http://localhost:8080
### register 
POST {{base_url}}/auth/user/register
Content-Type: application/json
{
    "name":"Pojok Code",
    "email":"code@gmail.com",
    "password":"P@ssw0rd"
}

### login
POST {{base_url}}/auth/user/login
Content-Type: application/json
{
    "email":"code@gmail.com",
    "password":"P@ssw0rd"
}

### refresh Token
GET {{base_url}}/auth/user/refresh