version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-net

networks:
  shared-net:
    external: true