version: "3.8"
services:
  commandbox:
    image: ortussolutions/commandbox
    ports:
      - "8888:8888"
      - "443:443"
    environment:
      PORT: 8888
      SSL_PORT: 443
      LUCEE_ADMIN_PASSWORDS: "admin:admin"
    volumes:
      - "./app:/app"
      - "./serverHome:/usr/local/lib/serverHome"
