@base_url=http://localhost:8080
### update user 
PUT {{base_url}}/payroll/user/update
Content-Type: application/json
{
    "name":"Pojok Code",
    "email":"code@gmail.com",
    "phone":"",
    "address":"",
    "password":"P@ssw0rd"
}